### ISSUE TITLE
what is database helper for searching row?

### ISSUE THREAD

**Issue by ghost** [openedoo/openedoo#68]
i have employee database. i want to search employee with some keyword. is there any helper in openedoo db tools that provide interface to mysql `select * from <table> where <columnname> like <keyword>` ?

**Comment by arissupriy** [comment]
from openedoo.core.db import Query
query.select_db(tables=od_users, column=od_users.user_id, value=user_id)

**Comment by arissupriy** [comment]
```python
from openedoo_project import db
class User(db.Model):
       username=username = db.Column(db.String(80), unique=True)
       ...... other
````
and then for select with where statement >> 
```python 
User.query.filter(username='value').all()
```

**Comment by ghost** [comment]
thank you. For now, i use sqlalchemy i get referenced from here http://docs.sqlalchemy.org/en/latest/orm/tutorial.html#common-filter-operators

This is the implentation in my code.
```
@module_employee.route('/search', methods=['GET', 'POST'])
def search():
    keyword = request.form['keyword']
    empl = User.query.filter(User.fullname.like("%"+keyword+"%")).all()
    for employee in empl:
        print employee.fullname
    return 'tes'
```
